export const sampleProducts = [
    {
        "ProductI": "NSR",
        "P/C": "Chai",
        "F/U": 1,
        "A/C": 1,
        "PART": "10 boxes x 20 bags",
        "PARTNAME": 18,
        "DUNS": 39,
        "SUPPLIERNAME": 0,
        "C/C": 10,
        "QTY": false,
        "Category": {
            "A/C": 1,
            "CategoryName": "Beverages",
            "Description": "Soft drinks, coffees, teas, beers, and ales"
        },
        "FirstOrderedOn": new Date(1996, 8, 20)
    },
    {
        "ProductI": 2,
        "P/C": "Chang",
        "F/U": 1,
        "A/C": 1,
        "PART": "24 - 12 oz bottles",
        "PARTNAME": 19,
        "DUNS": 17,
        "SUPPLIERNAME": 40,
        "C/C": 25,
        "QTY": false,
        "Category": {
            "A/C": 1,
            "CategoryName": "Beverages",
            "Description": "Soft drinks, coffees, teas, beers, and ales"
        },
        "FirstOrderedOn": new Date(1996, 7, 12)
    },
    {
        "ProductI": 3,
        "P/C": "Aniseed Syrup",
        "F/U": 1,
        "A/C": 2,
        "PART": "12 - 550 ml bottles",
        "PARTNAME": 10,
        "DUNS": 13,
        "SUPPLIERNAME": 70,
        "C/C": 25,
        "QTY": false,
        "Category": {
            "A/C": 2,
            "CategoryName": "Condiments",
            "Description": "Sweet and savory sauces, relishes, spreads, and seasonings"
        },
        "FirstOrderedOn": new Date(1996, 8, 26)
    },
   
];

export const products = [{
    "ASNTYPE": "NSR",
    "ASNCODE": "T",
    "P/C": "FW",
    "F/U": "K",
    "A/C": "EM",
    "A/R": "N",
    "PART": "22980433",
    "PARTNAME": "RR SHK ABK5",
    "DUNS": "003306750",
    "SUPPLIERNAME": "TENN/AUTO",
    "C/C": "US",
    "QTY": "150",
    "SHIPDATE": "2020-05-01",
    "EDA": " ",
    "ETA": " ",
    "ST": "0",
    "SID": " ",
    "PONUMBER": " ",
    "SHIPCOMMENT": " ",
    "M": " ",
    "NM": " ",
    "UM": " ",
    "CS": " ",
    "NCX": " ",
    "ROUTE": " ",
    "CARRIER": " ",
    "TRAILER": " ",
    "MANIFEST": " ",
    "SCAC": " ",
    "DOCK": " ",
    "DOCKSPOT": " ",
    "NUMBERCONT": " ",
    "TOTALPARTWT": " ",
    "PRO": " ",
    "PTA": " ",
    "RECVATDUNS": " ",
    "ERD": " ",
    "EDATOERDVARIANCE": " ",
    "ASN/SCHPK": " ",
    "ASN/STDPK": " "
}, {
     "ASNTYPE": "ASNO",
    "P/C": "FW",
    "F/U": "PO",
    "A/C": " ",
    "PART": "00686186",
    "PARTNAME": "ENVELOPE",
    "DUNS": "000243147",
    "SUPPLIERNAME": "SANDY CORSTE",
    "C/C": "US",
    "QTY": "10",
    "SHIPDATE": "2020-05-01",
    "EDA": "2020-05-05",
    "ETA": "0000",
    "ST": "0",
    "SID": " ",
    "PONUMBER": " ",
    "SHIPCOMMENT": " ",
    "M": " ",
    "NM": " ",
    "UM": " ",
    "CS": " ",
    "NCX": " ",
    "ROUTE": " ",
    "CARRIER": " ",
    "TRAILER": " ",
    "MANIFEST": " ",
    "SCAC": " ",
    "DOCK": " ",
    "DOCKSPOT": " ",
    "NUMBERCONT": " ",
    "TOTALPARTWT": " ",
    "PRO": " ",
    "PTA": " ",
    "RECVATDUNS": " ",
    "ERD": " ",
    "EDATOERDVARIANCE": " ",
    "ASN/SCHPK": " ",
    "ASN/STDPK": " "
}, {
     "ASNTYPE": "ASNO",
    "P/C": "FW",
    "F/U": " BG",
    "A/C": "NC",
    "PART": "23397296",
    "PARTNAME": "ROD-FRT S/D LK",
    "DUNS": "202679841",
    "SUPPLIERNAME": "MAGNA PENETANUG",
    "C/C": "CA",
    "QTY": "1400",
    "SHIPDATE": "2020-05-01",
    "EDA": "2020-05-07",
    "ETA": "1400",
    "ST": "0",
    "SID": " ",
    "PONUMBER": " ",
    "SHIPCOMMENT": " ",
    "M": " ",
    "NM": " ",
    "UM": " ",
    "CS": " ",
    "NCX": " ",
    "ROUTE": " ",
    "CARRIER": " ",
    "TRAILER": " ",
    "MANIFEST": " ",
    "SCAC": " ",
    "DOCK": " ",
    "DOCKSPOT": " ",
    "NUMBERCONT": " ",
    "TOTALPARTWT": " ",
    "PRO": " ",
    "PTA": " ",
    "RECVATDUNS": " ",
    "ERD": " ",
    "EDATOERDVARIANCE": " ",
    "ASN/SCHPK": " ",
    "ASN/STDPK": " "
    },
{
     "ASNTYPE": "ASNO",
    "P/C": "FW",
    "F/U": "77",
    "A/C": "EM",
    "PART": "23376229",
    "PARTNAME": "WHEEL-20X9.0J A",
    "DUNS": "000132233",
    "SUPPLIERNAME": "DICASTAL",
    "C/C": "US",
    "QTY": "176",
    "C/S": " ",
    "SHIPDATE": "2020-05-03",
    "EDA": "2020-05-10",
    "ETA": "0000",
    "ST": "0",
    "SID": " ",
    "PONUMBER": " ",
    "SHIPCOMMENT": " ",
    "M": " ",
    "NM": " ",
    "UM": " ",
    
    "NCX": " ",
    "ROUTE": " ",
    "CARRIER": " ",
    "TRAILER": " ",
    "MANIFEST": " ",
    "SCAC": " ",
    "DOCK": " ",
    "DOCKSPOT": " ",
    "NUMBERCONT": " ",
    "TOTALPARTWT": " ",
    "PRO": " ",
    "PTA": " ",
    "RECVATDUNS": " ",
    "ERD": " ",
    "EDATOERDVARIANCE": " ",
    "ASN/SCHPK": " ",
    "ASN/STDPK": " "
    }
];
